name: Watch GitHub  Actions.

on:
  workflow_run:
    workflows: [Send Microsoft Teams Notification]
    types:
      - completed

jobs:
  watch-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI (gh)
        run: |
          sudo apt-get install gh

      - name: Authenticate with GitHub CLI using github.token
        run: |
          gh auth login --with-token

      - name: Run tests
        run: |
          echo "Running tests..."
          # Simulate some test output
          echo "Test 1: Success"
          echo "Test 2: Fail"

      - name: Send logs to Teams
        if: always() # Run this step even if previous steps fail
        run: |
          # Capture logs from the current workflow run
          LOGS=$(cat $GITHUB_STEP_SUMMARY)

          # Create a JSON payload with the logs
          PAYLOAD=$(cat <<EOF
          {
            "text": "GitHub Action Logs: \n\n$LOGS"
          }
          EOF
          )

          # Send the logs to Teams via the Incoming Webhook
          curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41

    env:
      TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41
