name: Watch GitHub Actions and Send to Teams

on:
  workflow_run:
    workflows: ["notify"] # The name of the workflow you're watching
    types:
      - completed
 
jobs:
  watch-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI (gh)
      run: |
        sudo apt-get install gh

    - name: Authenticate with GitHub CLI using github.token
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh auth login --with-token <<< "${GH_TOKEN}"

    - name: Watch the workflow run
      id: watch_run
      run: |
       # Watch the workflow run and capture the output
        output=$(gh run watch --json conclusion,workflow,run_number -q '.workflow_runs[0].conclusion')
        echo "Output: $output"
        echo "::set-output name=result::$output"

    - name: Send notification to Microsoft Teams
      if: success() || failure()
      env:
        TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41
      run: |
        # Get the result from the previous step
        result="${{ steps.watch_run.outputs.result }}"
        
        # Prepare the message
        if [ "$result" == "success" ]; then
          status="successful"
        else
          status="failed"
        fi

        # Send the message to Teams
        curl -H "Content-Type: application/json" \
             -d "{\"text\": \"The workflow run has $status. Result: $result\"}" \
             "$TEAMS_WEBHOOK_URL"
