# name: Watch GitHub  Actions.

# on:
#   workflow_run:
#     workflows: [Send Microsoft Teams Notification]
#     types:
#       - completed

# jobs:
#   watch-job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Upload build artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: my-artifact-name
#           path: .github/workflows 

#       - name: Check out the repository
#         uses: actions/checkout@v3

#       - name: Set up GitHub CLI (gh)
#         run: |
#           sudo apt-get install gh

#       - name: Authenticate with GitHub CLI using github.token
#         # env:
#         #   GH_TOKEN: ${{ secrets.my_token }}
#         run: |
#           gh auth login --with-token

#       - name: Watch the workflow run
#         id: watch_run
#         run: |
#           output=$(gh run download ${GITHUB_RUN_ID})
#           echo "Output: $output"
#           echo "result=$output" >> $GITHUB_ENV

#       - name: Send notification to Microsoft Teams
#         if: success() || failure()
#         env:
#           TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41
#         run: |
#           result="${{ env.result }}"
#           if [ "$result" == "success" ]; then
#             status="successful"
#           else
#             status="failed"
#           fi

#           curl -H "Content-Type: application/json" \
#                -d "{\"text\": \"The workflow run has $status. Result: $result\"}" \
#                "$TEAMS_WEBHOOK_URL"
  