name: Send Microsoft Teams Notification

on:
  push:
    branches:
      - master

env:
  MS_TEAMS_WEBHOOK_URL: https://avaloqgroup.webhook.office.com/webhookb2/acc69694-4513-4770-9275-42f898a52f96@2ba8a4bf-3d7a-478b-b8d1-85cae49436ef/IncomingWebhook/ee99d20a71df4bb7993376f96e8a7427/9be00cee-8615-47cd-acdb-537181146f7d/V2vqRicQ0PbEBM-ImL6GUIwMByEgr2iZbJBdhuJXvNOV41

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-name
          path: .github/workflows 

      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Build Command
        run: |
          echo "Building the project.."
  
 
 